In [13]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import cv2
import time
import scipy.signal as conv

plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.cmap'] = 'gray'

In [14]:
im = cv2.imread("lena.png", 0)
print(np.amin(im), np.amax(im))

10 241


## Array indexing from dictionaries

In [15]:
from collections import OrderedDict

x = OrderedDict()
y = OrderedDict()

x[0] = [5,2,3,43,77] # col
y[0] = [5,2,3,4,11]  # row

print(x[0], y[0])
print(im[x[0], y[0]])

[5, 2, 3, 43, 77] [5, 2, 3, 4, 11]
[133 137 135 128 125]


## Return coordinates of array that has a specific value

In [16]:
r1,c1 = np.nonzero(im)
r2,c2 = np.where(im == 241)

print(np.shape(r1), np.shape(c1))
print(np.shape(r2), np.shape(c2))

(262144,) (262144,)
(2,) (2,)


# Sorting of multiple arrays

In [28]:
# Sort in ascending order
intensities = np.array([3,2,1,4,6])
indices = np.argsort(intensities)

# indices to sort
print(intensities[indices])

# gotta convert list to array before sorting
print(np.array(x[0])[indices])

[1 2 3 4 6]
[ 3  2  5 43 77]
